image: gcc

before_script:
 - apt-get update -qq
 - apt-get install libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev -y
 - export XDG_RUNTIME_DIR="$(mktemp -p $(pwd) -d xdg-runtime-XXXXXX)"
 - apt-get install cmake -y




test_Action:
    script:
        - cd tests/Action
        - make
        - ../run.sh
    artifacts:
        paths:
            - tests/Action/cov.txt
    stage: test


test_Clickable:
    script:
        - cd tests/Clickable
        - make
        - ../run.sh
    artifacts:
        paths:
            - tests/Clickable/cov.txt
    stage: test


test_DisplayCode:
    script:
        - cd tests/DisplayCode
        - make
        - ../run.sh
    artifacts:
        paths:
            - tests/DisplayCode/cov.txt
    stage: test


test_Element:
    script:
        - cd tests/Element
        - make
        - ../run.sh
    artifacts:
        paths:
            - tests/Element/cov.txt
    stage: test


test_Font:
    script:
        - cd tests/Font
        - make
        - ../run.sh
    artifacts:
        paths:
            - tests/Font/cov.txt
    stage: test


test_SANDAL2:
    script:
        - cd tests/SANDAL2
        - make
        - ../run.sh
    artifacts:
        paths:
            - tests/SANDAL2/cov.txt
    stage: test


test_Sprite:
    script:
        - cd tests/Sprite
        - make
        - ../run.sh
    artifacts:
        paths:
            - tests/Sprite/cov.txt
    stage: test


test_Window:
    script:
        - cd tests/Window
        - make
        - ../run.sh
    artifacts:
        paths:
            - tests/Window/cov.txt
    stage: test


coverage:
    script:
        - apt-get install bc -y
        - cd tests
        - ./coverage.sh
    stage: deploy
    dependencies:
        - test_Window
        - test_Sprite
        - test_SANDAL2
        - test_Font
        - test_Element
        - test_DisplayCode
        - test_Clickable
        - test_Action

    coverage: /coverage[:] ([0-9,\.]+%)/
